# Generated by Django 3.1 on 2021-07-05 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_count_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
